# Site wide configuration

title:            Raghava Mutharaju
locale:           en_US
url:


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Raghava Mutharaju
  avatar: bio-photo.jpg
  bio: "PhD student interested in Large Scale Computing, Ontology Reasoning, RDF, Semantic Web Applications and Knowledge Graph"
  email: mutharaju.2@wright.edu
  disqus-shortname:
  twitter: mraghava
  facebook: raghava.mutharaju
  google:
    plus: RaghavaMutharaju
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: raghavam
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: raghavamutharaju
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
